### ISSUE TITLE
Adding remote source authentication to plugin

### ISSUE THREAD

**Issue by anarwal** [rdilweb/docusaurus-plugin-remote-content#26]
Hello,

I was trying to use your plugin for my project's documentation however I hit a roadblock while downloading from remote source. As my file is on company's server (internal github) I will have to provide authentication token when fetching from source url. Do you have this functionality planned?

**Comment by RDIL** [comment]
Hey,
I actually had this thought a few days ago.  I'll implement this later today for you.

**Comment by anarwal** [comment]
Awesome! @RDIL that would be very helpful for me.

**Comment by RDIL** [comment]
Just released 2.1.0 with this feature.  It is now documented in the readme.

**Comment by anarwal** [comment]
@RDIL Thanks for this release. I saw another error when using "private github endpoints" to download remote file. It results in 
`[ERROR] Error [ERR_FR_TOO_MANY_REDIRECTS]: Maximum number of redirects exceeded`
which is caused by SSO redirect when using company's github endpoints. I saw adding `cookie-jar` (https://www.npmjs.com/package/axios-cookiejar-support and https://github.com/axios/axios/issues/48) would solve the problem for redirects. 

Any suggestions?

**Comment by RDIL** [comment]
You should be able to add `axios-cookiejar-support` to your project's dependencies, then apply it in your `docusaurus.config.js` by putting this at the top:
```js
const axios = require("axios")
const { wrapper } = require("axios-cookiejar-support")

wrapper(axios)
```
