### ISSUE TITLE
Allow path for content to be dynamic 

### ISSUE THREAD

**Issue by anarwal** [rdilweb/docusaurus-plugin-remote-content#29]
In order to use authorization with requestConfig, I am using github api and base url is like:
`sourceBaseUrl: "https://github.com/api/v3/repos/<org>/<repo>/contents/", `
in my repo the file I am trying to download is in a directory, so I have to use following documents value:
`documents: ["<dir-name>/<file-name>"]`

While downloading this `<dir-name>` gets appended to `output-dir`. This makes the file result-path to be <output-dir>/<original-dir>/<file-name>. 

Can you allow to provide `output-file` along with `output-dir`. This would make things a way lot easier to move the files around.

**Comment by RDIL** [comment]
A workaround for this is to have multiple different instances of the plugin with multiple output directories, but I'll see if I can add a setting for this before the next release.

**Comment by RDIL** [comment]
You can now do this using the `modifyContent` option.  See the readme for more details.
