### ISSUE TITLE
Directory download support

### ISSUE THREAD

**Issue by thomasheartman** [rdilweb/docusaurus-plugin-remote-content#30]
Hi! I was tipped about this plugin from the Docusaurus Discord and it looks like an amazing fit for what I was looking for; thank you for creating it 😄 

I was wondering whether there's any support for either downloading directories (including subdirectories) or downloading all files in a directory / at a url, or if that's planned at all? Judging from the readme, it doesn't look like it, but I thought I'd ask anyway.

Regardless of whether this is supported (or planned), the plugin still seems incredibly useful for my purposes; I just want to know what the limits are, so I can plan with them in mind. Thanks again!

**Comment by RDIL** [comment]
So yeah, you can, but it requires a bit of scripting.  The plugin is meant to be platform-independent so you will need to manually index the directories.  What you could do is something like this:

```js
// in plugin options
async documents() {
    const theDocuments = await makeSomeApiRequests()

    return theDocuments
}
```

**Comment by thomasheartman** [comment]
Ah, right! So if I understand you correctly, you just use that in place of the usual property? So, using the example from the readme, I'd get something like this:

```js
module.exports = {
    // ...
    plugins: [
        [
            "docusaurus-plugin-remote-content",
            {
                // options here
                name: "some-content", // used by CLI, must be path safe
                sourceBaseUrl: "https://my-site.com/content/", // the base url for the markdown (gets prepended to all of the documents when fetching)
                outDir: "docs", // the base directory to output to.
                async documents() {
                    const theDocuments = await makeSomeApiRequests()

                    return theDocuments
                }
            },
        ],
    ],
}
```

And the `theDocuments` is basically just the path to all the documents from the `sourceBaseUrl`, right?

Thank you!

**Comment by RDIL** [comment]
Yeah, an array of paths relative to the base URL.

**Comment by thomasheartman** [comment]
Thanks! That sounds like what I need 😄  I'll go ahead and close this issue, then.
