### ISSUE TITLE
Rename file on sync

### ISSUE THREAD

**Issue by ImmaZoni** [rdilweb/docusaurus-plugin-remote-content#33]
I was curious if there were any plans to allow a file to be renamed as its syncing to the directory, it would also be nice to be able to add front matter to the readme as to not have it required upstream for proper indexing, etc. 

Im sure this may be out of scope for the plugin but was curious of future plans, and would be happy to help where i can :)

**Comment by RDIL** [comment]
Hey,

This is something that was requested in the past, so I will add it to my to-do list for later this week.

**Comment by RDIL** [comment]
You can now do this using the `modifyContent` option.  See the readme for more details.
